# Generated by Django 4.0.6 on 2022-08-06 15:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Books',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('BookName', models.CharField(max_length=150)),
                ('Author', models.CharField(max_length=20)),
                ('publisher', models.CharField(max_length=100)),
                ('numofPages', models.CharField(max_length=100)),
                ('bookWebsite', models.URLField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Headings', models.CharField(max_length=100)),
                ('description', models.CharField(max_length=100)),
                ('createDate', models.DateTimeField()),
                ('book', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reviews', to='bookShop.books')),
            ],
        ),
    ]
