# Generated by Django 4.0.6 on 2022-08-06 15:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bookShop', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='review',
            old_name='Headings',
            new_name='Heading',
        ),
    ]
