# Generated by Django 4.0.6 on 2022-08-06 15:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookShop', '0002_rename_headings_review_heading'),
    ]

    operations = [
        migrations.AlterField(
            model_name='review',
            name='createDate',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
