# Generated by Django 4.0.6 on 2022-08-09 16:14

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('bookShop', '0002_alter_review_reviewer'),
    ]

    operations = [
        migrations.AlterField(
            model_name='review',
            name='Reviewer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
